CREATE SCHEMA IF NOT EXISTS BOOK_ANALYZER;

CREATE TABLE BOOK_ANALYZER.BOOK
(
    ID              BIGSERIAL NOT NULL,
    BOOK_AUTHOR     CHARACTER VARYING(200),
    BOOK_NAME       CHARACTER VARYING(200),
    GENRE           CHARACTER VARYING(100),
    YEAR_OF_PUBLISH INTEGER,
    PUBLISHER       CHARACTER VARYING(200),
    DESCRIPTION     TEXT,
    ISBN            CHARACTER VARYING(20),
    LANGUAGE        CHARACTER VARYING(2)
);

CREATE TABLE BOOK_ANALYZER.BOOK_CONTENT
(
    ID      BIGSERIAL NOT NULL,
    BOOK_ID BIGINT,
    CONTENT TEXT
);

CREATE TABLE BOOK_ANALYZER.BOOK_ANALYSIS
(
    ID           BIGSERIAL NOT NULL,
    BOOK_ID      BIGINT,
    LAUNCH_START TIMESTAMP,
    LAUNCH_END   TIMESTAMP,
    WORDS_COUNT  INTEGER
);

CREATE TABLE BOOK_ANALYZER.WORDS_USAGE_ANALYSIS
(
    BOOK_ANALYSIS_ID BIGINT,
    BOOK_ID          BIGINT,
    WORD             CHARACTER VARYING(200),
    OCCURRENCES      INTEGER
)