package com.akimrabinko.bookanalyzer.model.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.List;

@Getter
@RequiredArgsConstructor
public enum Language {
    AB(List.of("Abkhazian")),
    AA(List.of("Afar")),
    AF(List.of("Afrikaans")),
    AK(List.of("Akan")),
    SQ(List.of("Albanian")),
    AM(List.of("Amharic")),
    AR(List.of("Arabic")),
    AN(List.of("Aragonese")),
    HY(List.of("Armenian")),
    AS(List.of("Assamese")),
    AV(List.of("Avaric")),
    AE(List.of("Avestan")),
    AY(List.of("Aymara")),
    AZ(List.of("Azerbaijani")),
    BM(List.of("Bambara")),
    BA(List.of("Bashkir")),
    EU(List.of("Basque")),
    BE(List.of("Belarusian")),
    BN(List.of("Bengali")),
    BI(List.of("Bislama")),
    BS(List.of("Bosnian")),
    BR(List.of("Breton")),
    BG(List.of("Bulgarian")),
    MY(List.of("Burmese")),
    CA(List.of("Catalan", "Valencian")),
    CH(List.of("Chamorro")),
    CE(List.of("Chechen")),
    NY(List.of("Chichewa", "Chewa", "Nyanja")),
    ZH(List.of("Chinese")),
    CU(List.of("Church Slavonic", "Old Slavonic", "Old Church Slavonic")),
    CV(List.of("Chuvash")),
    KW(List.of("Cornish")),
    CO(List.of("Corsican")),
    CR(List.of("Cree")),
    HR(List.of("Croatian")),
    CS(List.of("Czech")),
    DA(List.of("Danish")),
    DV(List.of("Divehi", "Dhivehi", "Maldivian")),
    NL(List.of("Dutch", "Flemish")),
    DZ(List.of("Dzongkha")),
    EN(List.of("English")),
    EO(List.of("Esperanto")),
    ET(List.of("Estonian")),
    EE(List.of("Ewe")),
    FO(List.of("Faroese")),
    FJ(List.of("Fijian")),
    FI(List.of("Finnish")),
    FR(List.of("French")),
    FY(List.of("Western Frisian")),
    FF(List.of("Fulah")),
    GD(List.of("Gaelic", "Scottish Gaelic")),
    GL(List.of("Galician")),
    LG(List.of("Ganda")),
    KA(List.of("Georgian")),
    DE(List.of("German")),
    EL(List.of("Greek")),
    KL(List.of("Kalaallisut", "Greenlandic")),
    GN(List.of("Guarani")),
    GU(List.of("Gujarati")),
    HT(List.of("Haitian", "Haitian Creole")),
    HA(List.of("Hausa")),
    HE(List.of("Hebrew")),
    HZ(List.of("Herero")),
    HI(List.of("Hindi")),
    HO(List.of("Hiri Motu")),
    HU(List.of("Hungarian")),
    IS(List.of("Icelandic")),
    IO(List.of("Ido")),
    IG(List.of("Igbo")),
    ID(List.of("Indonesian")),
    IU(List.of("Inuktitut")),
    IK(List.of("Inupiaq")),
    GA(List.of("Irish")),
    IT(List.of("Italian")),
    JA(List.of("Japanese")),
    JV(List.of("Javanese")),
    KN(List.of("Kannada")),
    KR(List.of("Kanuri")),
    KS(List.of("Kashmiri")),
    KK(List.of("Kazakh")),
    KM(List.of("Central Khmer")),
    KI(List.of("Kikuyu", "Gikuyu")),
    RW(List.of("Kinyarwanda")),
    KY(List.of("Kirghiz", "Kyrgyz")),
    KV(List.of("Komi")),
    KG(List.of("Kongo")),
    KO(List.of("Korean")),
    KJ(List.of("Kuanyama", "Kwanyama")),
    KU(List.of("Kurdish")),
    LO(List.of("Lao")),
    LA(List.of("Latin")),
    LV(List.of("Latvian")),
    LI(List.of("Limburgan", "Limburger", "Limburgish")),
    LN(List.of("Lingala")),
    LT(List.of("Lithuanian")),
    LU(List.of("Luba-Katanga")),
    LB(List.of("Luxembourgish", "Letzeburgesch")),
    MK(List.of("Macedonian")),
    MG(List.of("Malagasy")),
    MS(List.of("Malay")),
    ML(List.of("Malayalam")),
    MT(List.of("Maltese")),
    GV(List.of("Manx")),
    MI(List.of("Maori")),
    MR(List.of("Marathi")),
    MH(List.of("Marshallese")),
    MN(List.of("Mongolian")),
    NA(List.of("Nauru")),
    NV(List.of("Navajo", "Navaho")),
    ND(List.of("North Ndebele")),
    NR(List.of("South Ndebele")),
    NG(List.of("Ndonga")),
    NE(List.of("Nepali")),
    NO(List.of("Norwegian")),
    NB(List.of("Norwegian Bokmal")),
    NN(List.of("Norwegian Nynorsk")),
    II(List.of("Sichuan Yi", "Nuosu")),
    OC(List.of("Occitan")),
    OJ(List.of("Ojibwa")),
    OR(List.of("Oriya")),
    OM(List.of("Oromo")),
    OS(List.of("Ossetian", "Ossetic")),
    PI(List.of("Pali")),
    PS(List.of("Pashto", "Pushto")),
    FA(List.of("Persian")),
    PL(List.of("Polish")),
    PT(List.of("Portuguese")),
    PA(List.of("Punjabi", "Panjabi")),
    QU(List.of("Quechua")),
    RO(List.of("Romanian", "Moldavian", "Moldovan")),
    RM(List.of("Romansh")),
    RN(List.of("Rundi")),
    RU(List.of("Russian")),
    SE(List.of("Northern Sami")),
    SM(List.of("Samoan")),
    SG(List.of("Sango")),
    SA(List.of("Sanskrit")),
    SC(List.of("Sardinian")),
    SR(List.of("Serbian")),
    SN(List.of("Shona")),
    SD(List.of("Sindhi")),
    SI(List.of("Sinhala", "Sinhalese")),
    SK(List.of("Slovak")),
    SL(List.of("Slovenian")),
    SO(List.of("Somali")),
    ST(List.of("Southern Sotho")),
    ES(List.of("Spanish", "Castilian")),
    SU(List.of("Sundanese")),
    SW(List.of("Swahili")),
    SS(List.of("Swati")),
    SV(List.of("Swedish")),
    TL(List.of("Tagalog")),
    TY(List.of("Tahitian")),
    TG(List.of("Tajik")),
    TA(List.of("Tamil")),
    TT(List.of("Tatar")),
    TE(List.of("Telugu")),
    TH(List.of("Thai")),
    BO(List.of("Tibetan")),
    TI(List.of("Tigrinya")),
    TO(List.of("Tonga (Tonga Islands)")),
    TS(List.of("Tsonga")),
    TN(List.of("Tswana")),
    TR(List.of("Turkish")),
    TK(List.of("Turkmen")),
    TW(List.of("Twi")),
    UG(List.of("Uighur", "Uyghur")),
    UK(List.of("Ukrainian")),
    UR(List.of("Urdu")),
    UZ(List.of("Uzbek")),
    VE(List.of("Venda")),
    VI(List.of("Vietnamese")),
    VO(List.of("Volapuk")),
    WA(List.of("Walloon")),
    CY(List.of("Welsh")),
    WO(List.of("Wolof")),
    XH(List.of("Xhosa")),
    YI(List.of("Yiddish")),
    YO(List.of("Yoruba")),
    ZA(List.of("Zhuang", "Chuang")),
    ZU(List.of("Zulu"));

    private final List<String> languages;
}
